export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-neutral-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-neutral-400 mb-10">Last updated: June 2026</p>

        <div className="space-y-8 text-neutral-600 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">1. Acceptance of terms</h2>
            <p>By creating an account or using Torvionyx, you agree to these Terms of Use. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">2. What Torvionyx is</h2>
            <p>Torvionyx is an AI-powered proposal generation tool for freelancers and consultants. It uses artificial intelligence to help you draft business proposals based on information you provide. The output is a starting point — you are responsible for reviewing, editing, and approving any proposal before sending it to a client.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">3. Your account</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must provide accurate information when creating your account</li>
              <li>You are responsible for keeping your login credentials secure</li>
              <li>You must be at least 18 years old to use Torvionyx</li>
              <li>One account per person or business</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">4. Acceptable use</h2>
            <p>You agree not to use Torvionyx to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Create fraudulent, misleading or deceptive proposals</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe the intellectual property rights of others</li>
              <li>Attempt to reverse engineer, scrape or abuse the service</li>
              <li>Use the service to harm, harass or defraud others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">5. Your content</h2>
            <p>You own all proposals and content you create using Torvionyx. By using the service, you grant us a limited licence to store and process your content solely to provide the service. We do not use your content to train AI models or share it with third parties beyond what is required to operate the platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">6. AI-generated content</h2>
            <p>Proposals generated by Torvionyx are produced by an AI model. We do not guarantee the accuracy, completeness or suitability of any AI-generated content. You are solely responsible for reviewing all proposals before sending them to clients. Torvionyx is not liable for any losses arising from the use of AI-generated proposals.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">7. Availability</h2>
            <p>We aim to keep Torvionyx available at all times but do not guarantee uninterrupted access. We may suspend or discontinue the service at any time, with or without notice, particularly during the beta period.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">8. Beta disclaimer</h2>
            <p>Torvionyx is currently in beta. This means the service is still being developed and may contain bugs, errors or unexpected behaviour. By using the beta, you accept that the service may change significantly or become unavailable.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">9. Limitation of liability</h2>
            <p>To the maximum extent permitted by law, Torvionyx is not liable for any indirect, incidental, special or consequential damages arising from your use of the service, including but not limited to lost revenue, lost clients or data loss.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">10. Termination</h2>
            <p>We may suspend or terminate your account at any time if you violate these terms. You may delete your account at any time by contacting us at torvionyx@gmail.com.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">11. Governing law</h2>
            <p>These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-900 mb-3">12. Contact</h2>
            <p>For any questions about these terms, contact us at <a href="mailto:torvionyx@gmail.com" className="text-cyan-600 hover:underline">torvionyx@gmail.com</a>.</p>
          </section>

        </div>

        <div className="mt-16 pt-8 border-t border-neutral-100">
          <a href="/" className="text-sm text-neutral-400 hover:text-neutral-600 transition-colors">← Back to Torvionyx</a>
        </div>
      </div>
    </div>
  );
}